# -*- coding: utf-8 -*-
"""logistic_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17hkVp8xzPoUVZEhMq67rHFu4SHsfchJz

<h2 style="color:green" align="center">Predicting if a person would buy life insurnace based on his age using logistic regression</h2>

Above is a binary logistic regression problem as there are only two possible outcomes (i.e. if person buys insurance or he/she doesn't).
"""

# Commented out IPython magic to ensure Python compatibility.
import streamlit as st
import pandas as pd
from sklearn.logistic_model import LogisticRegression
from matplotlib import pyplot as plt
# %matplotlib inline

st.set_page_config(
    page_title="INSURANCE Prediction",
    page_icon="🏠",
    layout="centered"
)
st.title(" INSURANCE Prediction")
st.write("Predict INSURANCE  price using LOGISTIC Regression")

# -----------------------------------
# Load Dataset
# -----------------------------------
df = pd.read_csv("insurance_data.csv")

st.subheader("Dataset")
st.dataframe(df)

# -----------------------------------
# Train Model
# -----------------------------------
X = df.drop("price", axis=1)
y = df["price"]

model = LogisticRegression()
model.fit(X, y)

# -----------------------------------
# User Input
# -----------------------------------
st.subheader("Enter age")

age = st.number_input(
    "age ( age )",
    min_value=0,
    max_value=100,
    value=10,
    step=1
)

# -----------------------------------
# Prediction
# -----------------------------------
if st.button("Predict Price"):

    prediction = model.predict([[age]])

    st.success(f"Predicted Price: ₹ {prediction[0]:,.2f}")

# -----------------------------------
# Model Information
# -----------------------------------
st.subheader("Model Details")

st.write("Coefficient:", model.coef_[0])
st.write("Intercept:", model.intercept_)

df = pd.read_csv("insurance_data.csv")
df.head()

plt.scatter(df.age,df.bought_insurance,marker='+',color='red')

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df[['age']],df.bought_insurance,train_size=0.8)

X_test

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train, y_train)

X_test

y_predicted = model.predict(X_test)

model.predict_proba(X_test)

model.score(X_test,y_test)

y_predicted

X_test

"""**model.coef_ indicates value of m in y=m*x + b equation**"""

model.coef_

"""**model.intercept_ indicates value of b in y=m*x + b equation**"""

model.intercept_

"""**Lets defined sigmoid function now and do the math with hand**"""

import math
def sigmoid(x):
  return 1 / (1 + math.exp(-x))

def prediction_function(age):
    z = 0.042 * age - 1.53 # 0.04150133 ~ 0.042 and -1.52726963 ~ -1.53
    y = sigmoid(z)
    return y

age = 35
prediction_function(age)

"""**0.485 is less than 0.5 which means person with 35 age will *not* buy insurance**"""

age = 43
prediction_function(age)

"""**0.485 is more than 0.5 which means person with 43 will buy the insurance**

<h2 style="color:purple">Exercise</h2>

Download employee retention dataset from here: https://www.kaggle.com/giripujar/hr-analytics.
1. Now do some exploratory data analysis to figure out which variables have direct and clear impact on employee retention (i.e. whether they leave the company or continue to work)
2. Plot bar charts showing impact of employee salaries on retention
3. Plot bar charts showing corelation between department and employee retention
4. Now build logistic regression model using variables that were narrowed down in step 1
5. Measure the accuracy of the model
"""